version: '3.9'

services:
  user-management:
    container_name: user-management
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3001:3000

  postgres:
    container_name: user-management-database
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data:U
    ports:
      - 8001:5432
