version: '3.9'

services:
  product-catalog:
    container_name: user-management-test
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq
    env_file:
      - .env
    command: sh -c 'npm run schema:drop && npm run migration:create && npm run migration:up && npm run test -- $E2E_TEST'
    ports:
      - 3001:3000

  postgres:
    container_name: user-management-database-test
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db_test:/var/lib/postgresql/data
    ports:
      - 8001:5432

  rabbitmq:
    container_name: user-management-message-broker
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    volumes:
      - ./data/messages:/var/lib/rabbitmq:U
    env_file:
      - .env
    ports:
      - 5999:5672
      - 15999:15672
