version: '3.9'

services:
  user-management:
    container_name: user-management
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3001:3000

  postgres:
    container_name: user-management-database
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
      #- ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 8001:5432

  adminer:
    container_name: user-management-adminer
    image: adminer
    restart: always
    ports:
      - '8901:8080'
