/* tslint:disable */
/* eslint-disable */
/**
 * User Managemenet API
 * The User Management API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterAdminHttpRequest
 */
export interface RegisterAdminHttpRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterAdminHttpRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAdminHttpRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAdminHttpRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAdminHttpRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAdminHttpRequest
     */
    lastName: string;
}

/**
 * Check if a given object implements the RegisterAdminHttpRequest interface.
 */
export function instanceOfRegisterAdminHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;

    return isInstance;
}

export function RegisterAdminHttpRequestFromJSON(json: any): RegisterAdminHttpRequest {
    return RegisterAdminHttpRequestFromJSONTyped(json, false);
}

export function RegisterAdminHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterAdminHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'password': json['password'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function RegisterAdminHttpRequestToJSON(value?: RegisterAdminHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'password': value.password,
        'firstName': value.firstName,
        'lastName': value.lastName,
    };
}

