/* tslint:disable */
/* eslint-disable */
/**
 * User Managemenet API
 * The User Management API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterMemberHttpRequest
 */
export interface RegisterMemberHttpRequest {
    /**
     * Username
     * @type {string}
     * @memberof RegisterMemberHttpRequest
     */
    username: string;
    /**
     * Password
     * @type {string}
     * @memberof RegisterMemberHttpRequest
     */
    password: string;
    /**
     * Email
     * @type {string}
     * @memberof RegisterMemberHttpRequest
     */
    email: string;
    /**
     * First Name
     * @type {string}
     * @memberof RegisterMemberHttpRequest
     */
    firstName: string;
    /**
     * Last Name
     * @type {string}
     * @memberof RegisterMemberHttpRequest
     */
    lastName: string;
}

/**
 * Check if a given object implements the RegisterMemberHttpRequest interface.
 */
export function instanceOfRegisterMemberHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;

    return isInstance;
}

export function RegisterMemberHttpRequestFromJSON(json: any): RegisterMemberHttpRequest {
    return RegisterMemberHttpRequestFromJSONTyped(json, false);
}

export function RegisterMemberHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterMemberHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function RegisterMemberHttpRequestToJSON(value?: RegisterMemberHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
    };
}

