/* tslint:disable */
/* eslint-disable */
/**
 * User Managemenet API
 * The User Management API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInHttpRequest
 */
export interface SignInHttpRequest {
    /**
     * Username
     * @type {string}
     * @memberof SignInHttpRequest
     */
    username: string;
    /**
     * Email
     * @type {string}
     * @memberof SignInHttpRequest
     */
    email: string;
    /**
     * Password
     * @type {string}
     * @memberof SignInHttpRequest
     */
    password: string;
}

/**
 * Check if a given object implements the SignInHttpRequest interface.
 */
export function instanceOfSignInHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function SignInHttpRequestFromJSON(json: any): SignInHttpRequest {
    return SignInHttpRequestFromJSONTyped(json, false);
}

export function SignInHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignInHttpRequestToJSON(value?: SignInHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'password': value.password,
    };
}

